spring.application.name=security-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/security_manager
spring.datasource.username=postgres
spring.datasource.password=secret123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=LFxm+Tut9XcAtz06SnIGVVVJVz4rKmLrCfCVhbeNmWA=

