version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: security-manager-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: security_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
